AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: retry429

Parameters:
  TargetHostTemplate:
    Type: String
    Description: |
      The host to target.
      Use <original_host> if you need to refer to the name under which the proxy is hosted.
      Typically, it is the domain name (generated or custom) that points to the generated API Gateway.
  TargetProtocol:
    Type: String
    AllowedValues:
      - http
      - https
  RetriedHttpStatuses:
    Type: String
    Description: Comma-separated HTTP statuses such as 429,503
  SubnetIds:
    Type: String
    Description: Comma-separated subnetIds such as subnetId1,subnetId2
    Default: ''
  SecurityGroupIds:
    Type: String
    Description: Comma-separated SecurityGroupIds such as sgId1,sgId2
    Default: ''
  SafeParamsChars:
    Type: String
    Description: Characters in queryParams that _not_ to be encoded as they are safe, such as []
    Default: ''

Globals:
  Function:
    Timeout: 600
    MemorySize: 128
    Tracing: Active
    Environment:
      Variables:
        TargetHostTemplate: !Ref TargetHostTemplate
        TargetProtocol: !Ref TargetProtocol
        RetriedHttpStatuses: !Ref RetriedHttpStatuses
        SubnetIds: !Ref SubnetIds
        SecurityGroupIds: !Ref SecurityGroupIds
        SafeParamsChars: !Ref SafeParamsChars

Conditions:
  HasExplicitVpcConfig: !Not [ !Equals [ '', !Ref SubnetIds ] ]

Resources:
  Retry429Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: retry_429/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - arm64
      VpcConfig:
        SubnetIds:
          'Fn::If':
            - HasExplicitVpcConfig
            - !Split [ ',', !Ref SubnetIds ]
            - [ ]
        SecurityGroupIds:
          'Fn::If':
            - HasExplicitVpcConfig
            - !Split [ ',', !Ref SecurityGroupIds ]
            - [ ]
      Events:
        AnyCall:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: any

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:
  Retry429Function:
    Value: !GetAtt Retry429Function.Arn
  Retry429FunctionIamRole:
    Value: !GetAtt Retry429FunctionRole.Arn
  Retry429HttpApiUrl:
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
