AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: retry429

Globals:
  Function:
    Timeout: 600
    MemorySize: 128
    Tracing: Active

Resources:
  Retry429Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: retry_429/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - arm64
      Events:
        AnyCall:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: any

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:
  Retry429Function:
    Value: !GetAtt Retry429Function.Arn
  Retry429FunctionIamRole:
    Value: !GetAtt Retry429FunctionRole.Arn
  Retry429HttpApiUrl:
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
